default_context:
  project_name: 'feedback'
  project_slug: 'feedback'
  domain_main: 'feedback.com'
  domain_staging: 'stg.feedback.com'
  docker_swarm_stack_name_main: 'feedback-com'
  docker_swarm_stack_name_staging: 'stg-feedback-com'
  secret_key: '5854b1249ba25be5f984be1529224f7f37d3b2a23f920e26be5205a74bacf060'
  first_superuser: 'bernardo.laing@gmail.com'
  first_superuser_password: 'Awdvcft13509'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.feedback.com", "https://stg.feedback.com", "https://feedback.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@feedback.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'bernardo.laing@gmail.com'
  pgadmin_default_user_password: 'Awdvcft13509'
  traefik_constraint_tag: 'feedback.com'
  traefik_constraint_tag_staging: 'stg.feedback.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Awdvcft13509'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
