"""seed auth permissions

Revision ID: 99a8c2083668
Revises: c9be3567e046
Create Date: 2022-01-18 14:40:24.588585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '99a8c2083668'
down_revision = 'c9be3567e046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = table(
        "permission",
        column("id", sa.Integer),
        column("key", sa.String),
        column("name", sa.String),
    )
    op.bulk_insert(
        permissions_table,
        [
            {"key": "user.create", "name": "Create a new User"},
            {"key": "user.list", "name": "Get the list of Users"},
            {"key": "user.edit", "name": "Edit  User's information"},
            {"key": "user.delete", "name": "Delete a user"},
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM permission WHERE key IN "
        "('user.create', 'user.list', 'user.edit', 'user.delete');"
    )
    # ### end Alembic commands ###
